openapi: 3.0.0
info:
  title: moviesSearcherAPI
  description: The API, used to search movie titles / movie lines based on input e.g. "thats not a knife" - "crocodile dundee", etc.
  version: 0.1.9
servers:
  - url: https://scriptsearcherapi.azurewebsites.net/api/movies
    description: movies API
paths:
  /search/{search}:
    get:
      summary: Returns matching movies
      description: returns a JSON file of movies. The movie title, the best matching line and the entire script
      parameters:
        - name: search
          in: path
          required: true
          description: search string a user inputs (/searchString)
          schema:
            type : string
            minimum: 0
      responses:
        '200':    # status code
          description: returns a JSON file of movies. The movie title, the best matching line and the entire script
          